version: '3.6'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # 모든 AWS 서비스는 이 포트 하나로 사용
    environment:
      - SERVICES=s3,sqs,sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=ap-northeast-2
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh  # 자동 리소스 생성 스크립트
      - localstack_data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - .:/app
      - staticfiles:/app/static
      - mediafiles:/app/media
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --access-logfile /var/log/gunicorn/access.log --error-logfile /var/log/gunicorn/error.log"

  # Cron job service (for scheduled tasks)
  cron-app:
    container_name: cron-app
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - .:/app
      - staticfiles:/app/static
      - mediafiles:/app/media
    networks:
      - app-network
    depends_on:
      - db
      - redis
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             fab2 update-crontab &&
             dos2unix command.cron &&
             chmod 0644 command.cron &&
             cat command.cron | crontab - &&
             service cron start &&
             tail -f /dev/null"

  # Nginx for load balancing between Blue and Green
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/static
      - mediafiles:/app/media
    networks:
      - app-network

  # PostgreSQL Database
  db:
    container_name: postgresql14
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    networks:
      - app-network
    tty: true
    logging:
      options:
        max-file: "7"
        max-size: "5m"

  # PgAdmin for managing the database
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5557:80"
    networks:
      - app-network
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      TZ: Asia/Seoul
    depends_on:
      - db

  # Redis cache server
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network
    ports:
      - "6379:6379"
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  mediafiles:
  localstack_data:
